### ISSUE TITLE
Исключение! Для расшифровки можете обратиться к разработчику напрямую или оставить issue на GitHub.

### ISSUE THREAD

**Issue by wollframium** [SmallTailTeam/BotLooter#81]
-

**Comment by wollframium** [comment]
в чем может быть ошибка, сегодня утром все еще работало

**Comment by wollframium** [comment]
ладно я допустил ошибку в кофиге все таки

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

The error occurs when trying to send a trade offer, likely due to an empty base URL. We'll modify the SteamWeb class to ensure a valid base URL is set for the RestClient used in SendTradeOffer.

You can review changes in this commit: https://github.com/lattaai13/SmallTailTeam-BotLooter-81/commit/bf414ad078e8455fcea52be0835b17129e00cd34.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
